### ISSUE TITLE
In doggo mode the ball should be controllable

### ISSUE THREAD

**Issue by Wiljami** [sjaks/demooni#10]
When thinking about it, it makes no sense that the dogs would toss the ball around with each other. I suggest the ball should move around either following the mouse cursor or be tossed around with mouse clicks.

**Comment by sjaks** [comment]
True, the app doesn't accurately reflect the real world at the moment. Needs to be fixed asap.

**Comment by sjaks** [comment]
Closing this since the dogs love to pass the ball around.
