### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by Wiljami** [sjaks/demooni#15]
Dogs should bark as they frolic across the screen. This would serve as a good audio cue to the user that something is happening.

This was mentioned in #1 already, but it was declared to be out of scope.

**Comment by sjaks** [comment]
Sound effects should be thought about. Demons could have some scary sound as well.

**Comment by sjaks** [comment]
Google Chrome blocks sounds by default and implementing this would require creating a landing screen that asks the user if sounds are allowed. This decreases UX. If there is a good way to force the sounds, this issue can be reopened!
