### ISSUE TITLE
Monkey mode

### ISSUE THREAD

**Issue by Wiljami** [sjaks/demooni#16]
Not everybody likes dogs. There should be a monkey mode with bananas. Monkeys also should have a thumb, while dogs don't have a thumb. There should be two kinds of monkeys: Helper monkeys and monkey companions.

**Comment by sjaks** [comment]
https://github.com/sjaks/demooni/commit/8cac410c41c1a45f7dc702b427d691e1df9672b9 introduces a monkey theme. The monkeys are unfortunately very similar to each other, so it is difficult to tell them apart.

The monkeys should still have thumbs.

**Comment by sjaks** [comment]
The emoji font only has a very human-like thumb icon and it's yellow. The monkeys cannot possibly have such thumbs. Closing this for now.
