### ISSUE TITLE
Optimize code

### ISSUE THREAD

**Issue by Wiljami** [sjaks/demooni#17]
Not everyone has top of the line computer able to run the demanding graphics. There should be a mode where you enable basic ascii characters as the entities on the screen instead of the high quality images.

**Comment by sjaks** [comment]
This program is a big pile of shitty, nonoptimized code. The emojis don't matter that much but that would be a step in the right direction. :+1:

**Comment by sjaks** [comment]
Included the optimization of images and such in https://github.com/sjaks/demooni/issues/30
