### ISSUE TITLE
Monkeys are not eating the bananas

### ISSUE THREAD

**Issue by Wiljami** [sjaks/demooni#18]
Monkeys are receiving bananas and instead of eating them, they're just passing them off??? This makes absolutely no sense.

**Comment by sjaks** [comment]
Stupid monkeys, what the hell??? This should be investigated.

What would happen when the banana is eaten? Any ideas, @elguitar, @Wiljami?

**Comment by sjaks** [comment]
Btw, in our vocabulary it's banaani, not banana. :smiley:

**Comment by sjaks** [comment]
Oh sorry, my bad. The documentation says:
> The monkeys don't seem to like the banana that much, so they pass it around, similarly to a packet.

This isn't weird at all. Closing this.
