### ISSUE TITLE
Demons should possess others

### ISSUE THREAD

**Issue by Wiljami** [sjaks/demooni#19]
Demons are known for their ability to possess other creatures. Now and then they should take over monkeys and dogs and possess them to do some kind of demonic action instead of their normal monkey or doggo behavior.

**Comment by sjaks** [comment]
Great idea :100:

**Comment by sjaks** [comment]
It's been a few months. We don't have the workforce to implement this.

**Comment by Wiljami** [comment]
Yes, this was haunting my assigned list on github as well.
