### ISSUE TITLE
There should be a spider monkey deity

### ISSUE THREAD

**Issue by Wiljami** [sjaks/demooni#29]
I find having only a monkey god is very limiting. Spider monkey deity should bring more flexibility and usability for the obvious reasons.

**Comment by sjaks** [comment]
What is the status of this?

**Comment by Wiljami** [comment]
The spider monkey deity eludes me. Its implementation is beyond the scope of my skills.

**Comment by sjaks** [comment]
Thus, this issue shall be closed.

**Comment by sjaks** [comment]
Thus, this issue shall be closed.
