### ISSUE TITLE
Refactor: Change packet variable name to pakeetti

### ISSUE THREAD

**Issue by elguitar** [sjaks/demooni#3]
Also, rename related functions accordingly.
For example,
`function movePacket()` should become `function liikutaPakeettia()`.

**Comment by sjaks** [comment]
Good idea. Maybe all function names should follow this: `luoDemooni()` for instance. Assigned you.

**Comment by elguitar** [comment]
Note: This should also affect CSS ids and classes.

**Comment by elguitar** [comment]
WIP in https://github.com/elguitar/demooni/tree/refactor/trans-vars

**Comment by sjaks** [comment]
What is the state of this? @elguitar I have new features planned that depend on the naming scheme.

**Comment by sjaks** [comment]
Notes:
```
daemon: demooni
packet: pakeetti
reitti: poloku
palkki: palakki
```
