### ISSUE TITLE
Add daemon handshake "scene"

### ISSUE THREAD

**Issue by Moppa5** [sjaks/demooni#5]
**Description**
Demons a.k.a daemons. In my opinion it could be nice if there was a some kind of handshake between the daemons before the packet "pakeetti" is sent to another daemon. This could also simulate for instance TLS handshake. 

Some other movement could also be added to daemons :)

**Comment by sjaks** [comment]
Indeed, the daemons should definitely have some movement but that is not priorized now.

The handhake scene is a nice idea and should be implemented next. After that this issue can be closed, I'd say.

**Comment by sjaks** [comment]
The daemons could have hands and toss the packets around. A proper handshake is a feature to be implemented in the future. This issue will be closed after the hands have been added and some random movement added to the daemons.

**Comment by sjaks** [comment]
Daemons now have hands and some random movement around their anchor point. Hand movement should be implemented next.
